# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EON Spark Data Visualization
email: stephen@pubnub.com
chatroom: https://goo.gl/forms/FltKTMbS8aduTlcu1
description: > # this means to ignore newlines until "baseurl:"
  Developers create engaging, beautiful
  live data visuals that helps you stand out.
  It is fast, simple, and open source.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stephenlb
github_username: stephenlb
github_reponame: eon-spark

## Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

## Minify
compress_html:
    comments: all
    clippings: all
    startings: all
    endings: all

